/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
InsertionSort insertionSort = new InsertionSort();
int[] arr = {8,4,23,42,16,15};
      System.out.println(Arrays.toString(insertionSort.insertionSort(arr)));
    }
}
