/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertEquals;

public class AppTest {
  @Test
  public void testInsertionSort() {
    InsertionSort insertionSort = new InsertionSort();
    int[] arr = {};
    assertEquals("[]", Arrays.toString(insertionSort.insertionSort(arr)));
    arr = new int[]{7};
    assertEquals("[7]", Arrays.toString(insertionSort.insertionSort(arr)));
    arr = new int[]{8, 4, 23, 42, 16, 15};
    assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(insertionSort.insertionSort(arr)));


  }
}
