/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testInsert (){
      LinkedList list = new LinkedList();
      assertEquals("",list.toString());
      list.insert(6);
      list.insert(7);
      list.insert(8);
      assertEquals("the expected output should be {8}->{7}->{6}->NULL","{8}->{7}->{6}->NULL",list.toString());
      assertEquals("The head should be the the last inserted number which is 5",5,list.insert(5));
    }
    @Test public void testIncludes(){
      LinkedList list = new LinkedList();
      list.insert(6);
      list.includes(6);
      assertTrue(list.includes(6));
      assertFalse(list.includes(9));
    }
}
