/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BreadthFirst;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class AppTest {
  @Test
  public void testBreadthFirst() {
    BreadthFirst bf = new BreadthFirst();
    Node A = new Node();
    Node B = new Node("test");


    assertEquals("[pandora, arendelle, metroville, monstroplis, narnia, naboo]", bf.graph().toString());
    assertEquals(null, bf.BreadthFirst(A));
    assertEquals("[test]", bf.BreadthFirst(B).toString());


  }
}
