/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {

    public static void main(String[] args) {
//      Hashtable hashTable= new Hashtable();
//      hashTable.add(123,"1");
//      hashTable.add(231,"2");
//      hashTable.add(321,"3");
//      System.out.println(hashTable.get(231));

    }
}
