/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {

    public static void main(String[] args) {
      Hashtable hashtable= new Hashtable();
      hashtable.add("ahmad","001233");
    }
}
