/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

import java.util.Arrays;

public class App {

  public static void main(String[] args) {
    TreeIntersection tree1 = new TreeIntersection();
    TreeIntersection tree2 = new TreeIntersection();
    Hashtable table = new Hashtable();

    tree1.add(22);
    tree1.add(15);
    tree1.add(3);
    tree1.add(52);
    tree1.add(17);
    tree1.add(27);
    tree1.add(82);
    tree1.add(10);
    tree1.add(32);
    tree2.add(7);
    tree2.add(52);
    tree2.add(11);
    tree2.add(10);
    tree2.add(3);
    tree2.add(24);
    tree2.add(32);
    System.out.println((tree2.commonValues(tree1.root,tree2.root)));
    System.out.println(table.arr[682]);



  }
}
