/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RepeatedWord;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class AppTest {
  @Test
  public void testRepeatedWord() {
    RepeatedWord repeated = new RepeatedWord();
    assertEquals("a", repeated.repeatedWord("Once upon a time, there was a brave princess who"));
  }
  @Test
  public void testRepeatedWord2() {
    RepeatedWord repeated = new RepeatedWord();
    assertEquals("there is no repeated words", repeated.repeatedWord("Hello i want to finish 401"));
  }
  @Test
  public void testRepeatedWord3() {
    RepeatedWord repeated = new RepeatedWord();
    assertEquals(null, repeated.repeatedWord(""));
  }
  @Test
  public void testRepeatedWord4() {
    RepeatedWord repeated = new RepeatedWord();
    assertEquals("summer",repeated.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York"));
  }
  @Test
  public void testRepeatedWord5() {
    RepeatedWord repeated = new RepeatedWord();
    assertEquals("it",repeated.repeatedWord("It the best of times, it was the worst of times,"));
  }
}
