/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;

public class App {


  public static void main(String[] args) {
    Stack stack = new Stack();
    Queue queue = new Queue();
//    stack.push(1);
//    stack.push(2);
//
//    System.out.println(stack.toString());
//
//
//    System.out.println(stack.peek());
////    System.out.println(stack.isEmpty());
//    System.out.println(stack.toString());

    queue.enqueue(1);
    queue.enqueue(2);
    queue.enqueue(3);
    System.out.println(queue.toString());
    System.out.println(queue.dequeue());
    System.out.println(queue.toString());
    System.out.println(queue.peek());
    System.out.println(queue.toString());
//    System.out.println(queue.isEmpty());
  }


}
