/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;

public class App {


  public static void main(String[] args) {
    Stack stack = new Stack();
    Queue queue = new Queue();

    ///////////////////// Stack //////////////////
//    stack.push(1);
//    stack.push(2);
////
//    System.out.println(stack.toString());
////
////
//    System.out.println(stack.peek());
//    System.out.println(stack.pop());
//    System.out.println(stack.pop());
//    System.out.println(stack.peek());
//    System.out.println(stack.isEmpty());
//    System.out.println(stack.toString());
/////////////////////// Queue //////////////////
//    queue.enqueue(10);
//    queue.enqueue(15);
//    queue.enqueue(20);
//    System.out.println(queue.toString());
//    System.out.println(queue.front.value);
//    System.out.println(queue.rear.value);

//    System.out.println(queue.dequeue());
//    System.out.println(queue.dequeue());
//    System.out.println(queue.dequeue());
//    System.out.println(queue.toString());
////    System.out.println(queue.front.value);
////    System.out.println(queue.rear.value);
//    System.out.println(queue.peek());
//    System.out.println(queue.toString());
//    System.out.println(queue.isEmpty());

//    PseudoQueue pseudoQueue = new PseudoQueue();
//
//    pseudoQueue.enqueue(20);
//    pseudoQueue.enqueue(15);
//    pseudoQueue.enqueue(10);
//    pseudoQueue.enqueue(5);
//
//    System.out.println(pseudoQueue.toString());
//    pseudoQueue.dequeue();
//    System.out.println(pseudoQueue.toString());


  }


}
