/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {


  public static void main(String[] args) {

    Graph graph = new Graph();
    Node A = graph.addNode("a");
    Node B = graph.addNode("b");
    Node C = graph.addNode("c");
    Node D = graph.addNode("d");
    graph.addEdge(A, 4, B);
    graph.addEdge(A, 9, D);
    graph.addEdge(A, 3, C);
    graph.addEdge(B, 5, D);
    graph.addEdge(C, 6, D);
    System.out.println(graph.getNeighbors(A));

  }

}
