/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
MergeSort mergeSort = new MergeSort();
int[] arr={8,4,23,42,16,15};

      System.out.println(Arrays.toString(mergeSort.mergesort(arr)));
    }
}
