/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ZipTwoLinkedLists;

public class App {

  public static void main(String[] args) {
    LinkedList list = new LinkedList();
    LinkedList2 list2 = new LinkedList2();
    list.insert(1);
    list.insert(1);
    list.insert(1);
    list2.insertTwo(2);
    list2.insertTwo(2);
    list2.insertTwo(2);
    System.out.println(list.zipLists(list, list2));
  }

}
