/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DepthFirst;

public class App {

    public static void main(String[] args) {
      DepthFirst DFT = new DepthFirst();
      DFT.graph();
    }
}
